name: run

on:
  workflow_dispatch:
    inputs:
      file_path:
        description: 'File URL from Telegram'
        required: true
      file_name:
        description: 'File name'
        required: true
      chat_id:
        description: 'Telegram ID'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download input file
        run: curl -L "${{ github.event.inputs.file_path }}" -o "${{ github.event.inputs.file_name }}"

      - name: Process the file
        run: |
          unzip "${{ github.event.inputs.file_name }}" -d input
          sudo apt-get update && sudo apt-get install openjdk-17-jdk-headless zipalign
          echo "Processing ${{ github.event.inputs.file_name }}..."
          for i in input/*; do
            java -jar redivision.jar $i
          done

      - name: Send output back to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          for i in redivision_*.jar; do
            curl -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendDocument" \
            -F chat_id="${{ github.event.inputs.chat_id }}" \
            -F document=@"redivision_${{ github.event.inputs.file_name }}" \
            -F caption="✅ Dex has been redistributed"
          done
