name: run

on:
  workflow_dispatch:
    inputs:
      file_path:
        description: 'File path in Telegram'
        required: true
      file_name:
        description: 'File name'
        required: true
      chat_id:
        description: 'Telegram ID'
        required: true
      caller_name:
        description: 'Username'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download input file
        run: curl -L "${{ github.event.inputs.file_path }}" -o "${{ github.event.inputs.file_name }}"

      - name: Process the file
        run: |
          unzip "${{ github.event.inputs.file_name }}"
          if [ -f framework.jar ]; then
            export patch=framework.jar
          elif [ -f services.jar ]; then
            export patch=services.jar
          elif [ -f miui-framework.jar ]; then
            export patch=miui-framework.jar
          elif [ -f miui-services.jar ]; then
            export patch=miui-services.jar
          else
            exit 1
          fi
          sudo apt-get update && sudo apt-get install openjdk-17-jdk-headless zipalign -y
          echo "Processing $patch..."
          java -jar redivision.jar $patch
          rm -rf $patch "${{ github.event.inputs.file_name }}"
          export DATE=$(TZ=UTC date +"%H%M")
          mv -f "redivision_$patch" "$DATE"_"$patch"
          ls && export patch="$DATE"_"$patch"
          echo "PATCH=$patch" >> "$GITHUB_ENV"

      - name: Send output back to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          if [ ! -f "$PATCH" ]; then
            echo "❌ Output file not found"
            exit 1
          fi
          echo "Sending: $PATCH"
          curl -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendDocument" \
            -F chat_id="${{ github.event.inputs.chat_id }}" \
            -F document=@"$PATCH" \
            -F caption="✅ Redistributed dex for ${{ github.event.inputs.caller_name }}"
